### ISSUE TITLE
Add raw data for data-raw folder 

### ISSUE THREAD

**Issue by larnsce** [openwashdata/cbssuitabilityhaiti#1]
Hi @mayalubecks

I have prepared a repository for your data. (Repo)sitory, is a fancy name for a folder/directory and you can picture it just like a folder that sits on your computer. You were added to the repo as collaborator, please accept that invitation. 

We will communicate and collaborate here using the so-called issue tracker. It helps us track organise tasks and track progress, but maybe most importantly, it reduces the number of emails in our inbox. :) 

You can respond here any time if you have questions or need support.

## Task 1: become a collaborator

- Accept the invitation from GitHub to join this repo as a collaborator

## Task 2: add your data to the repository

Your task now would be to add your raw data to the data-raw folder. You can do this directly here on GitHub, following these steps:

### Step 1

- Open the repository for your data: https://github.com/openwashdata/cbssuitabilityhaiti

### Step 2

- Open the data-raw folder

![Screenshot 2023-04-06 at 15 50 15](https://user-images.githubusercontent.com/18212549/230400494-c230cbe3-ad16-4f75-8086-f6c37e97de62.png)

### Step 3

- Click on "Add file -> Upload files"

![Screenshot 2023-04-06 at 15 50 35](https://user-images.githubusercontent.com/18212549/230400895-ee4f1657-ba57-45c1-91bb-f3780261d80e.png)

### Step 4

- Add your files
- Commit changes (this associates your GitHub username as a contribution to this repository)

![Screenshot 2023-04-06 at 15 50 56](https://user-images.githubusercontent.com/18212549/230403903-61fd06d5-fc09-402e-b44b-de8a801dac19.png)

### Step 5

- Let me know that you have submitted the data by responding to this issue and mention me using my GitHub handle `@larnsce`

**Comment by mayalubecks** [comment]
Hi Lars,

Thank you so much for these clear next steps. Unfortunately my inbox has
piled up recently so I didn't see that I needed to accept the invitation
within 7 days of being sent- could you please resend it and I will accept
it in time this time?

Thank you,
Maya

**Comment by larnsce** [comment]
Hi Maya, thanks for following up. I have sent out the invite again. :)

**Comment by mayalubecks** [comment]
Hi @larnsce, I have uploaded the spatial data files to the repository!

**Comment by larnsce** [comment]
Thank you, @mayalubecks. I will start exploring the data and get back to you with questions in a separate issue.
