### ISSUE TITLE
Provide authors/contributors information

### ISSUE THREAD

**Issue by sebastian-loos** [openwashdata/cbssuitabilityhaiti#3]
Hey @mayalubecks

I had a look into the datasets and I am excited about its content. Since one of the main goals of the openwashdata project is to give credit to all contributors to a dataset, we would like you to add the author information for the datasets to the repository.

You can do it in a similar way as you did with the dictionary. 

# Step 1
You can download the authors.xlsx file from the following link:

https://github.com/openwashdata/cbssuitabilityhaiti/raw/main/data-raw/authors.xlsx

# Step 2

Open the file on your computer and fill in the rows with the authors information:

- `first_name`, given names
- `last_name`, last names
- `email`
- `role`, provide one or more three-letter codes specifying the [role](https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/person) of the contributor.
These are the most common ones:
cre: creator or maintainer, maintains the package and is the contact person
aut: authors, made significant contributions 
ctb: contributors, made smaller contributions
dtc: data contributor,  contributed data sets
fnd: funder
- `orcid`, add the authors/contributors [Orcid number](https://orcid.org/) so that the data package can be linked automatically later on.

There are two examples already in the spread sheet.

# Step 3

Upload the completed authors.xlsx file back into the data-raw folder using the same steps as in Issue #1.

# 

Please feel free to add all known contributors, also the people who conducted/supervised a survey/interview or collected spatial data points for example. This way, everybody can get acknowledged and have a reference to show.

If you have any questions please go ahead and contact me.
Thank you very much for working through this with us!

**Comment by sebastian-loos** [comment]
If you would like to see how the authors are currently presented, please go to the page with the [drafted documentation](https://openwashdata.github.io/cbssuitabilityhaiti/) or to an already [published package](https://global-health-engineering.github.io/durbanplasticwaste/) page. You may also like to click `cite cbssuitabilityhaiti`.

**Comment by mayalubecks** [comment]
@sebastian-loos I just uploaded the authors sheet with added info for myself and Sasha Kramer. Unfortunately I don't have specific author names for the creators fo the datasets however I do have specific text that is supposed to be used for crediting the data:

World Bank flood extent data should be attributed with "Plan d’Élaboration propre basée sur les données de la Banque Mondiale: Inondation de Récurrence (5 ans / 25 ans / 100 ans)"

Sanitation zoning assessment data should be attributed with "These data were developed under the USAID Water and Sanitation Project in collaboration with the Cap-Haitian municipal government and DINEPA. These data do not reflect the opinion of USAID or the US Government."

I'm not sure how we can add these credits within the same format as the excel sheet you provided?

Thanks!

**Comment by larnsce** [comment]
Thanks a lot @mayalubecks for providing these details.

@sebastian-loos: The two additional references can be added to the documentation of the individual data sets and also shown on the README.rmd. An example that I often use is the palmerpenguins package. It's well done there:

- `README.rmd`: https://github.com/allisonhorst/palmerpenguins/blob/c19a904462482430170bfe2c718775ddb7dbb885/README.Rmd#L201
- `penguins.R` roxygen @source entry: https://github.com/allisonhorst/palmerpenguins/blob/c19a904462482430170bfe2c718775ddb7dbb885/R/penguins.R#L18

**Comment by sebastian-loos** [comment]
Thanks a lot @mayalubecks!

I did go ahead and included your added authors information to all the package documentation files. Do you and Sasha also have a Orcid ID? We will publish the data set package via Zenodo and it will get its own doi. It would help people to know your work and since it will show an additional publication in your Orcid account:)

You mentioned the World Bank flood extent data that can be found on [humdata.org](https://data.humdata.org/dataset/cap-haitien-haiti-flood-event-extents), right?

@larnsce I went through the commit history and saw that it is the dataset you removed in the beginning of the package making, do you remember why we did that? @mayalubecks I took a look into the data ([code](https://github.com/openwashdata/cbssuitabilityhaiti/blob/b077e07f816d9d1a5e53e933faf08f35165ac932/data-raw/read_flood-extent-data.R), [images](https://github.com/openwashdata/cbssuitabilityhaiti/tree/b077e07f816d9d1a5e53e933faf08f35165ac932/data-raw/maps)), what does it show exactly?

I included the accreditation text for the **Sanitation zoning assessment data** (okap). @larnsce can you check if that's the right way please?

- [`README.Rmd`](https://github.com/openwashdata/cbssuitabilityhaiti/blob/c048f8fcaca53fb9219111ef99941ac6146698b6/README.Rmd#L177-L181)
- [`okap.R`](https://github.com/openwashdata/cbssuitabilityhaiti/blob/c048f8fcaca53fb9219111ef99941ac6146698b6/R/okap.R)

I did not do it for the **World Bank flood extent data** since the data is not included in the package at the moment (can be discussed).

@mayalubecks Is there something I have to take into account for the **mwater data** ?

Thanks a lot for all your help!

**Comment by larnsce** [comment]
R data package is now complete and available at: https://openwashdata.github.io/cbssuitabilityhaiti/

ORCIDs of @mayalubecks and Sasha could still be added if provided.
